apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes/api-deployment.yaml
  - kubernetes/api-ingress.yaml
  - kubernetes/api-service.yaml
  - kubernetes/db-deployment.yaml
  - kubernetes/db-service.yaml
